# Generated by Django 2.2.6 on 2021-01-14 02:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_eval_objectives', '0001_initial'),
        ('jobs', '0011_auto_20201109_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRunSummary',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('job_eval_objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_eval_objectives.JobEvalObjective')),
            ],
        ),
    ]
