# Generated by Django 2.2.6 on 2021-01-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_run_summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrunsummary',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='jobrunsummary',
            name='job_eval_objective',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='job_eval_objectives.JobEvalObjective'),
            preserve_default=False,
        ),
    ]
