# Generated by Django 2.2.6 on 2021-01-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_run_summaries', '0003_jobrunsummary_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrunsummary',
            old_name='type',
            new_name='summary_type',
        ),
    ]
