# Generated by Django 2.2.6 on 2021-01-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_run_summaries', '0004_auto_20210123_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrunsummary',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
