# Generated by Django 2.2.6 on 2021-02-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_run_summaries', '0006_auto_20210125_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrunsummary',
            old_name='content_data_checksum',
            new_name='content_checksum',
        ),
        migrations.RenameField(
            model_name='jobrunsummary',
            old_name='content_data_path',
            new_name='content_path',
        ),
    ]
