services:
  api:
#    image: gr-api2
    build: ./api        
#    volumes:
#      - ./api:/api
    ports:
      - "8002:8002"

  web:
#    image: gr-gui2
    build: ./gui
#    volumes:
#      - ./gui:/gui
    ports:
      - "80:80"
      - "443:443"

