# Generated by Django 2.2.8 on 2020-02-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageBlob',
        ),
    ]
