# Generated by Django 2.2.6 on 2019-12-31 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workbooks.Workbook'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sequence',
            field=models.IntegerField(),
        ),
    ]
