# Generated by Django 2.2.6 on 2020-02-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='file_uuids_used',
        ),
    ]
