# Generated by Django 2.2.6 on 2020-10-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200614_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jobs.Job'),
        ),
    ]
