# Generated by Django 2.2.6 on 2020-11-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20201002_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='request_data',
            field=models.BinaryField(max_length=4000000000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='response_data',
            field=models.BinaryField(max_length=4000000000, null=True),
        ),
    ]
