# Generated by Django 2.2.6 on 2020-11-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20201107_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='request_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='response_data',
            field=models.TextField(null=True),
        ),
    ]
