# Generated by Django 3.2.4 on 2021-07-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20201109_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hostname',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
