# Generated by Django 2.2.6 on 2020-02-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0002_remove_workbook_file_uuids_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbook',
            name='owner',
        ),
    ]
