FROM node:10 AS build
RUN npm update npm
COPY redact-app /js
RUN cd /js && npm ci
RUN cd / && \
  git clone https://github.com/pscottdevos/regexp-tree.git regexp-tree && \
  cd /regexp-tree && \
  npm ci && \
  mv /regexp-tree/dist /js/node_modules/regexp-tree/
RUN cd /js && env PUBLIC_URL=/redact npm run build
WORKDIR /js
EXPOSE 3000/tcp
CMD ["npm", "start"]
