# Generated by Django 2.2.6 on 2020-02-25 19:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workbooks', '0001_initial'),
        ('jobs', '0003_job_updated'),
        ('scanners', '0001_initial'),
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipelines.Pipeline')),
                ('scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scanners.Scanner')),
                ('workbook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workbooks.Workbook')),
            ],
        ),
    ]
