# Generated by Django 2.2.6 on 2020-10-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_remove_attribute_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'default_related_name': 'attributes'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pipelines.Pipeline'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='scanners.Scanner'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='workbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='workbooks.Workbook'),
        ),
    ]
