# Generated by Django 2.2.6 on 2021-01-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_eval_objectives', '0001_initial'),
        ('job_run_summaries', '0004_auto_20210123_1634'),
        ('attributes', '0003_auto_20201002_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='job_eval_objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='job_eval_objectives.JobEvalObjective'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='job_run_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='job_run_summaries.JobRunSummary'),
        ),
    ]
